#web_messenger_chat_index:
#    methods: [GET]
#    path: chat
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\ChatController::index
#
#web_messenger_chat_create:
#    path: chat/create
#    methods: [GET,POST]
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\ChatController::create
#
#web_messenger_chat_view:
#    methods: [GET]
#    path: chat/view/{id}
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\ChatController::view
#    requirements:
#        id: '\d+'
#
#web_messenger_chat_update:
#    methods: [GET,POST]
#    path: chat/update/{id}
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\ChatController::update
#    requirements:
#        id: '\d+'
#
#web_messenger_chat_delete:
#    methods: [POST]
#    path: chat/delete/{id}
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\ChatController::delete
#    requirements:
#        id: '\d+'

# Message

web_messenger_chat_index:
    methods: [GET]
    path: messenger
    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::index

web_messenger_chat_list:
    methods: [GET]
    path: chat-list
    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::chatList

web_messenger_message_message-list:
    methods: [GET]
    path: message-list/{chatId}
    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::messageList

web_messenger_message_create:
    path: messenger/{chatId}
    methods: [POST]
    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::create
#
#web_messenger_message_view:
#    methods: [GET]
#    path: message/view/{id}
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::view
#    requirements:
#        id: '\d+'
#
#web_messenger_message_update:
#    methods: [GET,POST]
#    path: message/update/{id}
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::update
#    requirements:
#        id: '\d+'
#
#web_messenger_message_delete:
#    methods: [POST]
#    path: message/delete/{id}
#    controller: ZnBundle\Messenger\Symfony4\Web\Controllers\MessageController::delete
#    requirements:
#        id: '\d+'
